### ISSUE TITLE
Smudge error when checkout out a particular checksum

### ISSUE THREAD

**Issue by DJDavies2** [rmclaren/bufr-query#18]
I tried this:

git clone https://github.com/NOAA-EMC/bufr-query --branch develop
git checkout 65193ee3066f3f9977079e420be769926cb86342

and I got this error:

Downloading test/testinput/data/amdar_wmo_multi.bufr (200 KB)
Error downloading object: test/testinput/data/amdar_wmo_multi.bufr (3c53aa4): Smudge error: Error downloading test/testinput/data/amdar_wmo_multi.bufr (3c53aa41e4f4a16fc5f824dda5a7121139ad3fc1b3bc7c3d6d971e93552bcb51): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /net/data/users/frwd/roses/mi-be984/bufr-query/.git/lfs/logs/20240719T122823.547317552.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: test/testinput/data/amdar_wmo_multi.bufr: smudge filter lfs failed

I presume this isn't supposed to happen?

**Comment by rmclaren** [comment]
You need to checkout the develop branch...

**Comment by DJDavies2** [comment]
Is it possible to have a fixed revision?  There don't appear to be any tags and we don't want to have a moving version.

**Comment by rmclaren** [comment]
We will make tags eventually. You would have this problem in any case as NOAA EMC has decided that we are not allowed to use git lfs anymore... Your error is a consequence of this.

**Comment by rmclaren** [comment]
OK, created release tag v0.0.1. I will create a new release after I merge in MPI features.

**Comment by DJDavies2** [comment]
Thanks.
