### ISSUE TITLE
CMake project and version tag need to be sync'd up

### ISSUE THREAD

**Issue by srherbener** [rmclaren/bufr-query#30]
The latest version tag is `v0.0.4` which should be reflected in the CMake project version. Currently, the CMake version is set to 2.8.0:

https://github.com/NOAA-EMC/bufr-query/blob/9f0c0765ff04eeebadbdd23392d909f3cba32d7e/CMakeLists.txt#L12

The CMake project version number is what the find_package command sees when find_package is checking for a required version. Since the project version is 2.8.0 the find_package command in the ioda CMake config will always pass, even when the tagged version 0.0.2 in spack-stack-1.8.0 is found in the ioda build process.

https://github.com/JCSDA-internal/ioda/blob/4a65610af7ee59789403fcaa189c15a251395423/CMakeLists.txt#L62

The CMake project version in bufr-query should match the associated tag version to get the find_package command to properly accept/reject bufr-query versions.

Let's address this for `v0.0.4` by updating the project version in bufr-query to 0.0.4 and then moving the `v0.0.4` tag to the develop branch after the project version change is merged in. Hopefully, that will not cause much (if any) disturbance since the `v0.0.4` tag was recently added.

Before fixing the `v0.0.2` tag in the spack-stack-1.8.0 version, we may want to think more about how we should go about making this fix. So for now, I think it will be sufficient to repair the `v0.0.4` version and address the `v0.0.2` later (separately from this issue).

**Comment by rmclaren** [comment]
ooop, thanks @srherbener

**Comment by rmclaren** [comment]
@srherbener I fixed all the tags v0.0.1 through v0.0.4. They should now all have the correct version numbers for their tags.

**Comment by srherbener** [comment]
> @srherbener I fixed all the tags v0.0.1 through v0.0.4. They should now all have the correct version numbers for their tags.

@rmclaren thanks for going back and fixing all of the tags. Does that mean another PR is coming?

**Comment by srherbener** [comment]
If so, I would suggest keeping the original tags on the commits they are currently on, and creating new version numbers for the fixes. That is `v0.0.1` stays as is, and the fix is on `v0.0.1.1`, ditto for `v0.0.2` and `v0.0.3`. This will keep the build formula in spack-stack intact, plus it could get very confusing for someone debugging problems if on one machine `v0.0.2` points to one commit and on another machine points to another commit.

**Comment by rmclaren** [comment]
No PR's, I carefully created branches (locally) for each tag, updated the version string, and then swapped out the tags. 

Kinda to late...

**Comment by srherbener** [comment]
So the issues with this are with the `v0.0.1` and `v0.0.2` tags (since version `v0.0.3` and `v0.0.4` haven't been added to the spack-stack formula). The spack-stack formula keeps a sha256 checksum on the download file which will magically change (or at least that is my assumption) resulting in the formula breaking. If this is correct, then we are in the situation where the spack-stack formula will not be able to replicate what is already released and built (`v0.0.2`), which I think is not a good thing. If we update the sha256 checksums in the spack-stack formula, the formula will work again but will build something different than what used to be built. Plus the update to the formula will not be in the spack-stack-1.8.0 tagged commit so we would have to deal with that.

I really appreciate the effort to fix the older tags, but I think we should use new tags for the fixed bufr-query configurations.

I still have a local clone of bufr-query before these changes, so I should be able to get the old commit hash values.

**Comment by rmclaren** [comment]
Ok, if ou want to do that it woould be fine with me.

**Comment by rmclaren** [comment]
Where in spack-stack does it keep the checksum values? I searched that project and the only references I've seen are via for bufr-query are the tag number?

**Comment by rmclaren** [comment]
I looked at the **git reflog** and I believe the git hash is the one that ends in **a78d4c7**. Is that what you are seeing?

If so I can switch v0.0.2 back to this.

**Comment by srherbener** [comment]
Yes that is the correct hash. I've created a new issue to track how we resolve this - #33. Let's continue the discussion there please. Thanks.
