### ISSUE TITLE
Something is out of sync in this repo

### ISSUE THREAD

**Issue by srherbener** [rmclaren/bufr-query#32]
I'm seeing this message when I click on the `v0.0.2` tag in this repo:
```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```

I can actually see the contents of the commit (ie, the modification of the cmake project version to 0.0.2) but I just want to bring this to your attention so it can be fixed.

Thanks

**Comment by emilyhcliu** [comment]
When I click other versions, such as `v0.0.4`, I am seeing the same warning message.

**Comment by srherbener** [comment]
I'm guessing that this warning means that the commit hash associated with the tag has not been pushed to the NOAA-EMC/bufr-query repo. In other words a PR needs to be submitted with the new branches associated with each tag that gives this warning.

**Comment by rmclaren** [comment]
What are you clicking on?

**Comment by rmclaren** [comment]
I pushed those branches that are associated with those tags, does that change anything for you? I'm not seeing any issues when browsing the tags on my end...

**Comment by srherbener** [comment]
@rmclaren the warnings have gone away for me now. I think the push worked. Thanks for fixing this!

Before I close this issue, @emilyhcliu do the warnings go away for you too? Thanks!

**Comment by emilyhcliu** [comment]
> @rmclaren the warnings have gone away for me now. I think the push worked. Thanks for fixing this!
> 
> Before I close this issue, @emilyhcliu do the warnings go away for you too? Thanks!

Yes, I confirm that the warnings also go away for me.

**Comment by srherbener** [comment]
Great! thanks for checking @emilyhcliu
