### ISSUE TITLE
Recent release updates have broken the spack-stack build formula for this library

### ISSUE THREAD

**Issue by srherbener** [rmclaren/bufr-query#33]
The updated releases for `v0.0.1` and `v0.0.2` have tag.gz files associated with them. These are the files that spack-stack uses in it formula for building the bufr-query package. When I ask spack to report the checksums, I get this

```
Stephens-MBP:spack-stack stephenh$ spack checksum bufr-query
==> Selected 4 versions. 2 new versions
  0.0.4  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.4.tar.gz
  0.0.3  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.3.tar.gz
  0.0.2  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.2.tar.gz
  0.0.1  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.1.tar.gz

==> Enter number of versions to take, or use a command:
    [c]hecksum  [e]dit  [f]ilter  [a]sk each  [n]ew only  [r]estart  [q]uit
action> c
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.3.tar.gz
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.1.tar.gz
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.4.tar.gz
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.2.tar.gz

    version("0.0.4", sha256="cc21a298c03ee3a8938823301606e91c7b321005da284ebf2c9b25044bfcbad8")
    version("0.0.3", sha256="8981d3c3062b3f44f9b012fee06ee480e8aa85a45f216d02648e1a0e95ca5a4e")
    version("0.0.2", sha256="6256b134b236ae7b15f26cabebe09ff7aefe41ef6a85c84165fa996286fab2db")
    version("0.0.1", sha256="0aa36c970a30ea1b5887f0503453319a4552eefa9012133c0998d8c0365bd5ef")
```

which no longer match the checksums recorded in the spack-stack formula:

```
...
class BufrQuery(CMakePackage, PythonExtension):
    """The NOAA bufr-query Library can be used to read NCEP and WMO formated BUFR
    files using a simple interface that does not require the user to know the
    details of the BUFR format. Detailed documentation for the BUFR Library can
    be found at https://bufr-query.readthedocs.io/en/latest/index.html"""

    homepage = "https://github.com/NOAA-EMC/bufr-query"
    url = "https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.1.tar.gz"
    maintainers("srherbener", "rmclaren")

    license("Apache-2.0", checked_by="srherbener")

    version("0.0.2", sha256="b87a128246e79e3c76e3158d89823e2ae38e9ee1a5a81b6f7b423837bdb93a1f")
    version("0.0.1", sha256="001990d864533c101b93d1c351edf50cf8b5ccc575e442d174735f6c332d3d03")

...
```

We need to figure out a way forward with this situation. I think we have several options:

1. Back out these changes and restore the releases for `v0.0.1` and `v0.0.2` so that they are back in sync with the current spack-stack formula. This would require the commit hashes of the associated tags before the update which I should have in my local clone of the bufr-query repo. Here are those hashes:
  - commit 97367fcd59adf4863aba1a52189e20f9f66451af (tag: v0.0.1)
  - commit a78d4c79d72aef3a7046386090ee5c3c51554718 (tag: v0.0.2)

Then merge in the new commits with the fixes and tag those with new labels. Perhaps `v0.0.1.1` and `v0.0.2.1`?

2. Treat spack-stack-1.8.0 as if it did not contain the bufr-query package. This would require running `module unload bufr-query` from every environment setting that there has been an installation of spack-stack-1.8.0. Then you would either build bufr-query manually (with develop branch which is intact) or add bufr-query to your bundle cmake configuration.

3.  Try to patch all of the existing spack-stack-1.8.0 installations. This would require updating the spack-stack bufr-query formula, and then building add-on environments (aka, chained environemnts) containing the updated bufr-query packages (I suppose at this point, you could build v0.0.4) at every installation of spack-stack and update the instructions to source environments from the add-on environments.

I think option 3 contains way more work than is worthwhile, plus it is subject to many failure points due to the manual nature of patching everywhere. We should not pursue option 3.

I think that option 2 sounds easy to do, and we are going to have to do this in our CI containers anyway but this is very localized and once done is finished. The issue I see with option 2 is that the spack-stack formula is out of sync (broken), and if it is updated then it has lost the history of what has already been built and installed everywhere. Not only the spack-stack formula but the bufr-query repo has lost its own history of these releases as well and I can see that being problematic. 

My recommendation is for option 1. This preserves the history in both the spack-stack formula and the bufr-query repo and at this point is also easy to do. This also gives each center the option of how they want to deal with this issue. Some could choose to unload the bufr-query module while others could choose to build the add-on environment. 

What do others think?

**Comment by rmclaren** [comment]
@srherbener Thanks steve, I will back out those changes as you suggest (point the tags for v0.0.1 and v0.0.2 back to the commits consistent with the hash values you indicated). I will then proceed with the revised tags as you indicated.. So option 1..

**Comment by rmclaren** [comment]
OK, v0.0.1 and v0.0.2 should be pointed back to their original commits.

**Comment by rmclaren** [comment]
Created v0.0.1.1 and v0.0.2.1 tags which include update the VERSION number in the CMakeLists.txt file.

**Comment by srherbener** [comment]
Sounds great @rmclaren. Thanks!

**Comment by srherbener** [comment]
I'm seeing the correct checksums (and commit hashes) now:
```
Stephens-MBP:spack-stack stephenh$ spack checksum bufr-query
==> Selected 4 versions. 2 new versions
  0.0.4  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.4.tar.gz
  0.0.3  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.3.tar.gz
  0.0.2  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.2.tar.gz
  0.0.1  https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.1.tar.gz

==> Enter number of versions to take, or use a command:
    [c]hecksum  [e]dit  [f]ilter  [a]sk each  [n]ew only  [r]estart  [q]uit
action> c
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.4.tar.gz
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.1.tar.gz
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.2.tar.gz
==> Fetching https://github.com/NOAA-EMC/bufr-query/archive/refs/tags/v0.0.3.tar.gz

    version("0.0.4", sha256="cc21a298c03ee3a8938823301606e91c7b321005da284ebf2c9b25044bfcbad8")
    version("0.0.3", sha256="8981d3c3062b3f44f9b012fee06ee480e8aa85a45f216d02648e1a0e95ca5a4e")
    version("0.0.2", sha256="b87a128246e79e3c76e3158d89823e2ae38e9ee1a5a81b6f7b423837bdb93a1f")
    version("0.0.1", sha256="001990d864533c101b93d1c351edf50cf8b5ccc575e442d174735f6c332d3d03")

```

Thank you very much for the quick response! I'll close this issue now.

**Comment by rmclaren** [comment]
Great to know!  Thanks for your patience...
